---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    opentelemetry: enabled
  name: iot-agent
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
    spec:
      containers:
      - env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: GOMEMLIMIT
          valueFrom:
            resourceFieldRef:
              containerName: iot-agent
              resource: limits.memory
        - name: CONTROL_PORT
          value: "8000"              
        - name: DEV_MGMT_URL
          value: http://iot-device-mgmt
        - name: MQTT_HOST
          valueFrom:
            secretKeyRef:
              name: authn-mqtt
              key: mqtt-host
        - name: MQTT_USER
          valueFrom:
            secretKeyRef:
              name: authn-mqtt
              key: mqtt-user
        - name: MQTT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: authn-mqtt
              key: mqtt-password
        - name: MSG_FWD_ENDPOINT
          value: http://iot-agent/api/v0/messages
        - name: RABBITMQ_HOST
          value: rabbitmq
        image: ghcr.io/diwise/iot-agent:changeme
        imagePullPolicy: IfNotPresent
        name: iot-agent
        ports:
          - containerPort: 8080
            name: default-port
            protocol: TCP
          - containerPort: 8000
            name: control-port
            protocol: TCP
        startupProbe:
          httpGet:
            path: /healthz
            port: control-port
        readinessProbe:
          httpGet:
            path: /readyz
            port: control-port
        livenessProbe:
          httpGet:
            path: /livez
            port: control-port
        resources:
          limits:
            cpu: 250m
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 100Mi            
        volumeMounts:
        - mountPath: /opt/diwise/config
          name: conf-volume
      serviceAccountName: iot-agent
      volumes:
        - name: conf-volume
          configMap:
            name: iot-agent-cfg-cm