---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot-agent
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
    spec:
      containers:
      - env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: DEV_MGMT_URL
          value: http://iot-device-mgmt.$(POD_NAMESPACE).svc.cluster.local
        - name: MQTT_HOST
          valueFrom:
            secretKeyRef:
              name: authn-mqtt
              key: mqtt-host
        - name: MQTT_TOPIC_0
          valueFrom:
            secretKeyRef:
              name: authn-mqtt
              key: mqtt-topic
        - name: MQTT_USER
          valueFrom:
            secretKeyRef:
              name: authn-mqtt
              key: mqtt-user
        - name: MQTT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: authn-mqtt
              key: mqtt-password
        - name: RABBITMQ_DISABLED
          value: "true"
        - name: MSG_FWD_ENDPOINT
          value: http://iot-agent.$(POD_NAMESPACE).svc.cluster.local/api/v0/messages
        image: ghcr.io/diwise/iot-agent:changeme
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /health
            port: default-port
        name: iot-agent
        ports:
        - containerPort: 8080
          name: default-port
          protocol: TCP
        resources:
          limits:
            cpu: 250m
            memory: 250Mi
          requests:
            cpu: 50m
            memory: 100Mi
        startupProbe:
          httpGet:
            path: /health
            port: default-port
      serviceAccountName: iot-agent
